# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE:
  - REPOSITORY
  - JSON
  - JAVASCRIPT
  - CSS
  - HTML
  - COPYPASTE
  - PYTHON
DISABLE_LINTERS:
  - YAML_V8R
  - SPELL_LYCHEE
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
PRINT_ALL_FILES: false
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3008 --ignore DL4006 --ignore DL3009 --ignore DL3059"
ADDITIONAL_EXCLUDED_DIRECTORIES: ["import", "megalinter-reports/"]
BASH_SHFMT_ARGUMENTS: "-i 4"
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: true
EMAIL_REPORTER: false
FILEIO_REPORTER: false
