# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none
DISABLE:
  - SPELL
  - REPOSITORY
  - JSON
  - MARKDOWN
  - JAVASCRIPT
  - CSS
  - HTML
  - COPYPASTE
  - PYTHON
DISABLE_LINTERS:
  - YAML_V8R
PRINT_ALL_FILES: false
BASH_SHFMT_ARGUMENTS: "-i 4"
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3008 --ignore DL4006 --ignore DL3009 --ignore DL3059"
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
